// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcx0bGhGVYNXhN865DOHlsQp73XTTEeNY',
    appId: '1:907467608466:web:1ffa2c19dfbcaf987fb14b',
    messagingSenderId: '907467608466',
    projectId: 'hrlynx-b9477',
    authDomain: 'hrlynx-b9477.firebaseapp.com',
    storageBucket: 'hrlynx-b9477.firebasestorage.app',
    measurementId: 'G-N3ZPHG14ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgD6I2WbbtTAYA84tHyD8NCO4ZHz_Li2M',
    appId: '1:907467608466:android:a846c7ee9c534a9a7fb14b',
    messagingSenderId: '907467608466',
    projectId: 'hrlynx-b9477',
    storageBucket: 'hrlynx-b9477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALWoZUBzrnW_fSdGtJ-BbN9XS_XDV0iwk',
    appId: '1:907467608466:ios:82fdd9586e3f65c77fb14b',
    messagingSenderId: '907467608466',
    projectId: 'hrlynx-b9477',
    storageBucket: 'hrlynx-b9477.firebasestorage.app',
    androidClientId: '907467608466-au8d6pts9a6c730rgn2fd70easikehah.apps.googleusercontent.com',
    iosClientId: '907467608466-9c7kk86ghtfqrvou3hpk3m45uj3sg07v.apps.googleusercontent.com',
    iosBundleId: 'com.lynxova.hrlnyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALWoZUBzrnW_fSdGtJ-BbN9XS_XDV0iwk',
    appId: '1:907467608466:ios:592f0c676c68b7007fb14b',
    messagingSenderId: '907467608466',
    projectId: 'hrlynx-b9477',
    storageBucket: 'hrlynx-b9477.firebasestorage.app',
    androidClientId: '907467608466-au8d6pts9a6c730rgn2fd70easikehah.apps.googleusercontent.com',
    iosClientId: '907467608466-1otrqqbqplp45e8su92jeoa9iat795p0.apps.googleusercontent.com',
    iosBundleId: 'com.bdCalling.hr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcx0bGhGVYNXhN865DOHlsQp73XTTEeNY',
    appId: '1:907467608466:web:608a8f0445d3b8e47fb14b',
    messagingSenderId: '907467608466',
    projectId: 'hrlynx-b9477',
    authDomain: 'hrlynx-b9477.firebaseapp.com',
    storageBucket: 'hrlynx-b9477.firebasestorage.app',
    measurementId: 'G-76170BG77P',
  );

}